### ISSUE TITLE
Please help the Iranian peoples with sharing script for easy setup LightWay vpn server 

### ISSUE THREAD

**Issue by hosein-moayedi** [expressvpn/lightway-core#57] opened 2022-10-05 11:49 UTC
Hi there!
I am an Iranian developer.
If you subscribe to the news, IRAN has blocked all protocols with DPI we can't connect to VPN. We need yours help for setup this protocol with simple script because LightWay protocol not detected by DPI right now and express VPN is working with this protocol.

We can't buy an express VPN for some problems in communicating with national banks and payment getaways. So, we just can setup our VPN servers.

IRAN needs your help

Please make an update and simple script with the last version of lightway-core and replay the link to this message 🙏

I very tried to use from lightway-laser but that is a very old source and I had some issues and errors.

**Comment by mohammadsadeghforoughi** [comment] 2022-10-10 11:51
Does anybody hear us? 
@expressvpn-lee-a  
@expressvpn-pete-m 
@expressvpn-raihaan-m

**Comment by expressvpn-pete-m** [comment] 2022-10-12 08:48
Sorry to hear that you're having trouble building Laser!

Our builds are configured to always pull the latest version of Lightway Core during the build process, and so the build should never become outdated. You mentioned you had some issues and errors - could you please share the errors and the messages that you're seeing?

We are committed to ensuring that Laser always works with Lightway Core as it is how people try out, verify and validate the technology. If the build system is broken for whatever reason, we will do our best to get it working again.

Thanks!

**Comment by EbrahimTahernejad** [comment] 2022-10-18 23:20
I successfully ran it
the issue is the tcp protocol 
when we use the Express VPN app, the only way we can connect is lightway-tcp 
so ... is there any plans to add tcp support anytime soon?

this is one of the few protocols that work for us still

**Comment by EbrahimTahernejad** [comment] 2022-10-18 23:22
> Hi there! I am an Iranian developer. If you subscribe to the news, IRAN has blocked all protocols with DPI we can't connect to VPN. We need yours help for setup this protocol with simple script because LightWay protocol not detected by DPI right now and express VPN is working with this protocol.
> 
> We can't buy an express VPN for some problems in communicating with national banks and payment getaways. So, we just can setup our VPN servers.
> 
> IRAN needs your help
> 
> Please make an update and simple script with the last version of lightway-core and replay the link to this message 🙏
> 
> I very tried to use from lightway-laser but that is a very old source and I had some issues and errors.

`touch /usr/include/stropts.h`
Do this before building, the libuv library includes this but doesn't use it, also don't forget to install 
build-essentials

**Comment by EbrahimTahernejad** [comment] 2022-10-18 23:24
> Sorry to hear that you're having trouble building Laser!
> 
> Our builds are configured to always pull the latest version of Lightway Core during the build process, and so the build should never become outdated. You mentioned you had some issues and errors - could you please share the errors and the messages that you're seeing?
> 
> We are committed to ensuring that Laser always works with Lightway Core as it is how people try out, verify and validate the technology. If the build system is broken for whatever reason, we will do our best to get it working again.
> 
> Thanks!

I successfully ran it
the issue is the tcp protocol
when we use the Express VPN app, the only way we can connect is lightway-tcp
so ... is there any plans to add tcp support anytime soon?

this is one of the few protocols left that still work for us

**Comment by expressvpn-pete-m** [comment] 2022-10-20 03:50
I have wanted to add TCP support for a while, and there is a PR that was started by @sheharyaar here : 

https://github.com/expressvpn/lightway-laser/pull/2

At the time we were getting some weird errors when reading from the socket.

I'll take another look at this as @sheharyaar did put in a lot of effort - but feel free to also take a look.

**Comment by abtinji** [comment] 2022-10-22 04:39
@EbrahimTahernejad , lightway_tcp doesn't connect to expressvpn servers since last 3 days for me, Are you still able to connect with lightway_tcp?

@expressvpn-pete-m , ExpressVPN can't get activated with IPs sourced from iran, Not really sure but that seems the activation requests goes to the third party servers which are probably hosted on AWS or such, where Iran's IPs are blocked due to US sanctions. I'm not quiet sure about the authentication mechanism, but have you guys made any changes for authentication process recently?

Here is my diagnostic logs, Running on Centos7 :

Lightway: 1.28.1 Lightway Core: 1.6.2 WolfSSL: 5.4.0 libxenon: 1.5.0 libballoon: 1.8.0
Loading config data from file: /var/run/expressvpn/config/he2931587164/helium.conf
Lightway will connect to 244.107.70.227:443 using protocol: tcp, cipher: aes, mtu: 1500
Lightway TCP connection established with 244.107.70.227:443
Lightway is CONNECTING
Received signal: 15
he_execute: starting /usr/sbin/expressvpnd --update-dns-config=static_resolv_conf
he_execute: process exited 0 (signal 0)
Lightway DISCONNECTED (disconnect_and_stop).
Lightway STOPPED
Lightway FINISHED
Disconnected with error: vpn connection timeout

**Comment by expressvpn-pete-m** [comment] 2022-10-23 16:42
Although I can't debug individual connection issues with the ExpressVPN App here, by the looks of it, you aren't able to establish a TLS session as there is no mention of authentication (probably due to some sort of timeout).

**Comment by sajjadintel** [comment] 2022-11-27 21:04
Please help Iranians the only protocol connects is lightway.

**Comment by MrAliSalehi** [comment] 2022-11-27 21:06
> Please help Iranians the only protocol connects is lightway. 

they will close the lightway as well, just a matter of time.

**Comment by rezarms** [comment] 2022-12-27 10:25
@EbrahimTahernejad  I'm a little confused.
Were you able to run lightway on your own server and using Expressvpn app to connect to your custom server?

**Comment by expressvpn-pete-m** [comment] 2023-08-28 03:04
I'm going to close this issue now as it hasn't been updated in many months. We are working on a new improved version of the Lightway implementation that will come with an improved client and server. This will be easier to set up and use in any environment.

**Closed by expressvpn-pete-m** 2023-08-28 03:04 UTC

**Comment by fromhgbwithluv** [comment] 2026-06-13 12:39
Uhm imo [VPN over DNS](https://github.com/masterking32/MasterDnsVPN) can be used to bypass Iran traffic blocker
